apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
      - name: java1
        image: sachinsids/webapp-demo:03